Vagrant.configure("2") do |config|
  config.vm.box_url = "/home/ehsan/Softwares/ubuntu16.04-libvirt.box"
  config.vm.define "k-master" do |app|
    app.vm.box = "ubuntu-libvirt"
    app.vm.hostname = "k-master"
    app.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 3072
      libvirt.cpus = 2
    end
    app.vm.network :private_network, ip: "192.168.102.101"
  end
  config.vm.define "k-slave-1" do |app|
    app.vm.box = "ubuntu-libvirt"
    app.vm.hostname = "k-slave-1"
    app.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 3072
      libvirt.cpus = 2
    end
    app.vm.network :private_network, ip: "192.168.102.102"
  end
  config.vm.define "k-slave-2" do |app|
    app.vm.box = "ubuntu-libvirt"
    app.vm.hostname = "k-slave-2"
    app.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 3072
      libvirt.cpus = 2
    end
    app.vm.network :private_network, ip: "192.168.102.103"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
